### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by paulvickers** [real-aazam/hollywood#1]
typing `hollywood -h` brings up the help options as expected. But when I just typed `hollywood` I got the following output:

```
can't find pane: hollywood
can't find pane: hollywood
can't find session: hollywood
```
I realised I had some old tmux sessions running and hollywood seemed to not play nicely with those. Once I killed those sessions it did seem to run.

**Comment by real-aazam** [comment]
ok, glad it's working fine now.
